# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"%\n\x12\x42ookCreateResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\t\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x8c\x01\n\x04\x42ook\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1e\n\x05genre\x18\x04 \x01(\x0e\x32\x0f.Book.GenreType\x12\x13\n\x0bPublishYear\x18\x05 \x01(\x05\"0\n\tGenreType\x12\x0b\n\x07\x46iction\x10\x00\x12\x0b\n\x07\x46\x61ntasy\x10\x01\x12\t\n\x05Novel\x10\x02\"\xa1\x01\n\rInventoryItem\x12\x17\n\x0fInventoryNumber\x18\x01 \x01(\x05\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.InventoryItem.StatusType\"&\n\nStatusType\x12\r\n\tavailable\x10\x00\x12\t\n\x05taken\x10\x01\x42\r\n\x0b\x42ookObjects2c\n\x10InventoryService\x12*\n\nCreateBook\x12\x05.Book\x1a\x13.BookCreateResponse\"\x00\x12#\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x05.Book\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKCREATERESPONSE._serialized_start=19
  _BOOKCREATERESPONSE._serialized_end=56
  _GETBOOKREQUEST._serialized_start=58
  _GETBOOKREQUEST._serialized_end=86
  _BOOK._serialized_start=89
  _BOOK._serialized_end=229
  _BOOK_GENRETYPE._serialized_start=181
  _BOOK_GENRETYPE._serialized_end=229
  _INVENTORYITEM._serialized_start=232
  _INVENTORYITEM._serialized_end=393
  _INVENTORYITEM_STATUSTYPE._serialized_start=340
  _INVENTORYITEM_STATUSTYPE._serialized_end=378
  _INVENTORYSERVICE._serialized_start=395
  _INVENTORYSERVICE._serialized_end=494
# @@protoc_insertion_point(module_scope)
